# AI-generated CI/CD Pipeline for python on AWS - Review Carefully!
name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - master

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

  test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run tests
        run: |
          source venv/bin/activate
          pytest || true

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Package application
        run: |
          zip -r app.zip . -x '*.git*' -x 'venv/*'

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-package
          path: app.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: app-package

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Set up SSH
        run: |
          echo "${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}" > ./ai-devops-ec2-key.pem
          chmod 600 ./ai-devops-ec2-key.pem

      - name: Deploy to EC2
        env:
          SSH_KEY_PATH: ./ai-devops-ec2-key.pem
          EC2_USER: ubuntu
          EC2_HOST: 34.203.191.194
        run: |
          scp -i $SSH_KEY_PATH -o StrictHostKeyChecking=no app.zip $EC2_USER@$EC2_HOST:~/app.zip
          ssh -i $SSH_KEY_PATH -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST << 'EOF'
            unzip -o ~/app.zip -d ~/app
            cd ~/app
            source venv/bin/activate
            pip install -r requirements.txt
            # Restart application service here, e.g., systemctl restart myapp
          EOF